global:
  scrape_interval: 15s # How often to poll your app

scrape_configs:
  - job_name: 'secureshare-api'
    static_configs:
      # This tells Prometheus to look at your .NET container on port 8080
      - targets: ['secureshare-api:8080']